[package]
name = "rend3-types"
version = "0.2.0"
authors = ["The rend3 Developers"]
edition = "2021"
description = "Type definitions for rend3"
readme = "../README.md"
repository = "https://github.com/BVE-Reborn/rend3"
license = "MIT OR Apache-2.0 OR Zlib"
keywords = ["3d", "graphics", "gpu", "renderer", "wgpu"]
categories = ["game-development", "graphics", "rendering", "rendering::engine"]
rust-version = "1.57"


[dependencies]
bitflags = "1"
glam = "0.20.0"
thiserror = "1"
wgt = { package = "wgpu-types", version = "0.11" }
